image: ruby:2.5.1

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - HANAMI_ENV=test bundle exec hanami db prepare
    - bundle exec rake
