AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.5.1

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'apps/web/application.rb'

Lint/ScriptPermission:
  Exclude:
    - 'bin/*'
